version: "3.7"
services:
  mail-service:
    container_name: mail-service
    image: mail-service
    build: .
    restart: always
    ports:
      - 8085:8085
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mail-mysqldb
      MYSQL_PORT: 3306
    depends_on:
      - mail-mysqldb
  mail-mysqldb:
    image: mysql
    container_name: mail-mysqldb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: mail
      MYSQL_ROOT_PASSWORD: root